### ISSUE TITLE
Bulk option?

### ISSUE THREAD

**Issue by yaoberh** [infinyte7/Sentence-Adder-Anki-Addon#2]
Is it possible to make sentences in bulk? Only 1 per card, but not having to do each one manually?

**Comment by infinyte7** [comment]
It is updated with batch add option view tutorial here
AnkiWeb
https://ankiweb.net/shared/info/1682655437

Tutorials
https://www.youtube.com/playlist?list=PLuy0icdF039z-kYxCLCmD3xdUynmFNbas

**Comment by yaoberh** [comment]
Working! Very cool :)
