### ISSUE TITLE
Problem with word matching

### ISSUE THREAD

**Issue by yaoberh** [infinyte7/Sentence-Adder-Anki-Addon#4]
If a word is contained within another word, for example
et is contained within toil**et**te
Then the sentence generator considers toilette as a valid sentence for et, which it isn't obviously and et is a different word in french.

**Comment by infinyte7** [comment]
I figured it out. 
https://github.com/infinyte7/Sentence-Adder-Anki-Addon/blob/main/src/editor.py#L69

For Chinese sentences it works perfectly because Chinese sentences do not contains spaces. But codes needs to change for language which contains spaces.

```
sql = "Select sentence from examples where sentence like " + "' %" + word + "% '"
#                                                                                                 ^^                      ^^  added space here
```
It will works.

**Comment by infinyte7** [comment]
Download updated addon from [AnkiWeb](https://ankiweb.net/shared/info/1682655437)  and try it. It will work now with spaces also.

**Comment by yaoberh** [comment]
Working!
