### ISSUE TITLE
Error with tsv file

### ISSUE THREAD

**Issue by EmmanuelVRdz** [infinyte7/Sentence-Adder-Anki-Addon#6]
Hi, I was the one that rate bad a few hours ago because of an error. Here is my preview message and below I add the files you requested me:

[deutsch_sentences TSV file.zip](https://github.com/infinyte7/Sentence-Adder-Anki-Addon/files/6231942/deutsch_sentences.TSV.file.zip)
[english_sentences TSV file.zip](https://github.com/infinyte7/Sentence-Adder-Anki-Addon/files/6231956/english_sentences.TSV.file.zip)
[frances_sentences TSV file.zip](https://github.com/infinyte7/Sentence-Adder-Anki-Addon/files/6231968/frances_sentences.TSV.file.zip)
[japanesse_sentences TSV file.zip](https://github.com/infinyte7/Sentence-Adder-Anki-Addon/files/6231970/japanesse_sentences.TSV.file.zip)

Hi, I've tried many times to launch the addon but it keeps sending me an error when I try to load the language data with the tsv document. Could you please assist me with this one? I´m a little bit stuck right now. I will update de rating when everything runs ok! ok?

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-30 00:34:31

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Valde\AppData\Roaming\Anki2\addons21\1682655437\__init__.py", line 95, in createDB
    for row in reader:
  File "C:\python\lib\codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 10: invalid start byte

**### Update**: Here I attach images of what appears today 30/03/2021

![image](https://user-images.githubusercontent.com/79390388/113052769-c30b8000-9164-11eb-8bf2-e137ee46dc8d.png)
![image](https://user-images.githubusercontent.com/79390388/113052934-f948ff80-9164-11eb-9315-d61875135a9c.png)
![image](https://user-images.githubusercontent.com/79390388/113052992-09f97580-9165-11eb-8419-8e183a2c9833.png)
![image](https://user-images.githubusercontent.com/79390388/113053272-5644b580-9165-11eb-8810-2ee5905a57d5.png)

If I try once again it sends me this:
![image](https://user-images.githubusercontent.com/79390388/113053397-75dbde00-9165-11eb-8892-c4ad2094dbd8.png)
 
But actually, there's no language loaded:
![image](https://user-images.githubusercontent.com/79390388/113053531-973cca00-9165-11eb-850c-921b5acc33d4.png)

And, to be clear, it happens with all of the tsv files, with all the 4 languages that I tried to upload

Something to consider is that in the files directory of the addon it does appear the language:
![image](https://user-images.githubusercontent.com/79390388/113054466-ae2fec00-9166-11eb-8d02-c2ed8992eb18.png)
![image](https://user-images.githubusercontent.com/79390388/113054567-ca338d80-9166-11eb-8231-30106c6272e4.png)

**Comment by infinyte7** [comment]
Did you downloaded from https://tatoeba.org/eng/downloads?
When I open in notepad I view this.
![1](https://user-images.githubusercontent.com/12841290/113055686-7617c000-91dd-11eb-97f1-8532a1976924.PNG)


But it should be like this. Three fields 
id lang sentences
![2](https://user-images.githubusercontent.com/12841290/113055697-79ab4700-91dd-11eb-9bf4-530e9596c1ab.PNG)

There is problem with tsv files.

**Comment by EmmanuelVRdz** [comment]
Yes, but it is beacuase you didn't decompres the files, that´s why you can´t see it in order with the noteblock. I sent them still compresed, because gitHub don't let us to upload them decompresed, I think it doesn´t admit tsv files. But the error is still remaining.




![image](https://user-images.githubusercontent.com/79390388/113074892-25767780-9189-11eb-8733-0b2720200ce9.png)

![image](https://user-images.githubusercontent.com/79390388/113075158-a9306400-9189-11eb-94f1-886fcbb44588.png)

![image](https://user-images.githubusercontent.com/79390388/113075175-b77e8000-9189-11eb-9fd8-5a4a6cbfb8cf.png)

### **Update:** This is the real error I was trying to shre with you!!

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-30 00:34:31

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Valde\AppData\Roaming\Anki2\addons21\1682655437\__init__.py", line 112, in selectFileFolderDlg
    if self.filepath.split("/")[-1].split(".")[1] == "tsv":
IndexError: list index out of range

![image](https://user-images.githubusercontent.com/79390388/113075494-47242e80-918a-11eb-9bb4-398c31f61b16.png)

**Comment by infinyte7** [comment]
The file again compressed with .tsv extension. I have extracted again to view the file.

The errors occur because this project only read .tsv file. So, if the file extension is not matching .tsv, it shows error.
So, rename those file with .tsv extension and try again. It  may works.

1. Changing file name with .tsv
![demo_tsv](https://user-images.githubusercontent.com/12841290/113102462-a76dab80-9230-11eb-8400-52a2301bd2cb.gif)

2. Creating db with those files

![demo_tsv1](https://user-images.githubusercontent.com/12841290/113103248-9ec9a500-9231-11eb-835f-c6cf47e89fbd.gif)

**Comment by EmmanuelVRdz** [comment]
### **THANK YOU VERY MUCH**

It was exactly what you said. the file extension was the issue. When changing the file extension to .tsv the files were able to be uploaded

![image](https://user-images.githubusercontent.com/79390388/113113674-cab04080-91c7-11eb-945b-4c934079806d.png)
![image](https://user-images.githubusercontent.com/79390388/113114102-3eeae400-91c8-11eb-8e09-e5986c1ef504.png)
